name: CI Taskwise Service

on:
  workflow_dispatch:

jobs: 
  tests:
    runs-on: ubuntu-latest
    env: 
      BASE_URL: 'http://localhost:3000'

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v5.0.0

      - name: Instalando as dependências
        run: npm install

      - name: Iniciando o servidor da aplicação
        run: npm start &

      - name: Executando os testes com mocha
        run: npm test
